### PR TITLE
added dio 3 support

### PR DESCRIPTION
**Pull request by amreniouinnovent**
added dio 3 support which works on FLutter Web
#2

### CODE REVIEW

**Comment by zeucxb** [comment]
👀

**Comment by zeucxb** [comment]
@aloisdeniel is this project still alive?

**Comment by zeucxb** [comment]
@amreniouinnovent why don't you publish your version of this package?

**Comment by amreniouinnovent** [comment]
@zeucxb I didn't publish a new package because it is just 3 files I took them and I put it directly to my project

**Comment by aloisdeniel** [comment]
Sorry for being slow! Been busy lately, and as I stopped using Dio a while ago (because is didn't support web yet), this plugin isn't in the top of my priority list.

Really need to add Github actions to accelerate the publishing process too.

**Comment by amreniouinnovent** [comment]
@aloisdeniel Dio support web in version 3
Thank you for merging my PR

**Pull request merged**
